name: test-gh
"on":
  push:
    branches:
      - develop
    paths-ignore:
    - 'docs/**'
    - '*.md'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
    - 'docs/**'
    - '*.md'

jobs:
  test-all:
    name: Test GH
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version: [v1.27.0, v1.31.0, latest]
    steps:
    - name: install kind
      uses: helm/kind-action@v1
      with:
        install_only: true
    - name: Resolve Kubernetes version
      id: resolve-k8s-version
      run: |
        k8s_version=${{ matrix.k8s-version }}
        if [ "${k8s_version}" = "latest" ]; then
          k8s_version=$(curl -Ls -o /dev/null -w %{url_effective} https://github.com/kubernetes/kubernetes/releases/latest | grep -oE 'tag/v[0-9]+\.[0-9]+\.[0-9]+' | cut -d'/' -f2)
          echo "Resolved latest k8s version to: $k8s_version"
        fi
        echo "k8s_version=$k8s_version" >> $GITHUB_ENV
    - name: Create Kind Cluster(k8s version ${{ env.k8s_version }})
      run: |
        k8s_version=${{ env.k8s_version }}
        kind create cluster --image kindest/node:${k8s_version}
    - name: Verify kind and k8s version
      run: |
        kind version
        kubectl version
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - name: Install Carvel Tools
      uses: carvel-dev/setup-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        only: ytt, kapp, kbld
        ytt: v0.45.4
        kapp: v0.58.0
        kbld: v0.37.5
    - name: Run Tests
      run: |
        set -e -x

        mkdir /tmp/bin
        export PATH=/tmp/bin:$PATH

        ./hack/verify-no-dirty-files.sh

        export SECRETGEN_E2E_NAMESPACE=secretgen-test

        ./hack/test-all.sh
